// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access_logs.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccessLog = `-- name: CreateAccessLog :one
INSERT INTO access_logs (employee_id, status)
VALUES($1, $2)
RETURNING id
`

type CreateAccessLogParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	Status     Status      `json:"status"`
}

func (q *Queries) CreateAccessLog(ctx context.Context, arg CreateAccessLogParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createAccessLog, arg.EmployeeID, arg.Status)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getAccessLogs = `-- name: GetAccessLogs :many
SELECT al.id, e.full_name, nt.uid, al.status, al.timestamp
FROM access_logs al
JOIN employees e ON e.id = al.employee_id
JOIN nfc_tags nt ON nt.id = al.nfc_tag_id
ORDER BY al.timestamp DESC
`

type GetAccessLogsRow struct {
	ID        pgtype.UUID        `json:"id"`
	FullName  string             `json:"full_name"`
	Uid       string             `json:"uid"`
	Status    Status             `json:"status"`
	Timestamp pgtype.Timestamptz `json:"timestamp"`
}

func (q *Queries) GetAccessLogs(ctx context.Context) ([]GetAccessLogsRow, error) {
	rows, err := q.db.Query(ctx, getAccessLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccessLogsRow
	for rows.Next() {
		var i GetAccessLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Uid,
			&i.Status,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
