// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: access_logs.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccessLog = `-- name: CreateAccessLog :one
INSERT INTO access_logs (employee_id, nfc_tag_id, door_id, status)
VALUES($1, $2, $3, $4)
RETURNING id
`

type CreateAccessLogParams struct {
	EmployeeID uuid.UUID `json:"employee_id"`
	NfcTagID   uuid.UUID `json:"nfc_tag_id"`
	DoorID     uuid.UUID `json:"door_id"`
	Status     Status    `json:"status"`
}

func (q *Queries) CreateAccessLog(ctx context.Context, arg CreateAccessLogParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createAccessLog,
		arg.EmployeeID,
		arg.NfcTagID,
		arg.DoorID,
		arg.Status,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getAccessLogs = `-- name: GetAccessLogs :many
SELECT al.id, e.full_name, nt.uid, d.door_name, al.status, al.created_at
FROM access_logs al
JOIN employees e ON e.id = al.employee_id
JOIN nfc_tags nt ON nt.id = al.nfc_tag_id
JOIN doors d ON d.id = al.door_id
ORDER BY al.created_at DESC
`

type GetAccessLogsRow struct {
	ID        uuid.UUID          `json:"id"`
	FullName  string             `json:"full_name"`
	Uid       string             `json:"uid"`
	DoorName  string             `json:"door_name"`
	Status    Status             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAccessLogs(ctx context.Context) ([]GetAccessLogsRow, error) {
	rows, err := q.db.Query(ctx, getAccessLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccessLogsRow
	for rows.Next() {
		var i GetAccessLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Uid,
			&i.DoorName,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
