// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getDeviceById = `-- name: GetDeviceById :one
SELECT id, device_name, mac_address, can_create, created_at FROM devices
WHERE id = $1
`

func (q *Queries) GetDeviceById(ctx context.Context, id uuid.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceById, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DeviceName,
		&i.MacAddress,
		&i.CanCreate,
		&i.CreatedAt,
	)
	return i, err
}

const getDeviceByMac = `-- name: GetDeviceByMac :one
SELECT id, device_name, mac_address, can_create, created_at FROM devices
WHERE mac_address = $1
`

func (q *Queries) GetDeviceByMac(ctx context.Context, macAddress string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByMac, macAddress)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DeviceName,
		&i.MacAddress,
		&i.CanCreate,
		&i.CreatedAt,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, device_name, mac_address, can_create, created_at FROM devices
ORDER BY device_name
`

func (q *Queries) ListDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.Query(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.DeviceName,
			&i.MacAddress,
			&i.CanCreate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDeviceCanCreate = `-- name: UpdateDeviceCanCreate :one
UPDATE devices
SET
    can_create = $1
WHERE id = $2
RETURNING id
`

type UpdateDeviceCanCreateParams struct {
	CanCreate bool      `json:"can_create"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) UpdateDeviceCanCreate(ctx context.Context, arg UpdateDeviceCanCreateParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateDeviceCanCreate, arg.CanCreate, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
