// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getDeviceById = `-- name: GetDeviceById :one
SELECT id, device_name, mac_address, can_create, created_at FROM devices
WHERE id = $1
`

func (q *Queries) GetDeviceById(ctx context.Context, id uuid.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceById, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DeviceName,
		&i.MacAddress,
		&i.CanCreate,
		&i.CreatedAt,
	)
	return i, err
}

const updateDeviceCanCreate = `-- name: UpdateDeviceCanCreate :one
UPDATE devices
SET
    can_create = $1
WHERE id = $2
RETURNING id
`

type UpdateDeviceCanCreateParams struct {
	CanCreate bool      `json:"can_create"`
	ID        uuid.UUID `json:"id"`
}

func (q *Queries) UpdateDeviceCanCreate(ctx context.Context, arg UpdateDeviceCanCreateParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateDeviceCanCreate, arg.CanCreate, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
