// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: doors.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getDoorByDeviceId = `-- name: GetDoorByDeviceId :one
SELECT id, door_name, device_id, created_at, updated_at FROM doors
WHERE device_id = $1
`

func (q *Queries) GetDoorByDeviceId(ctx context.Context, deviceID uuid.UUID) (Door, error) {
	row := q.db.QueryRow(ctx, getDoorByDeviceId, deviceID)
	var i Door
	err := row.Scan(
		&i.ID,
		&i.DoorName,
		&i.DeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDoorById = `-- name: GetDoorById :one
SELECT id, door_name, device_id, created_at, updated_at FROM doors
WHERE id = $1
`

func (q *Queries) GetDoorById(ctx context.Context, id uuid.UUID) (Door, error) {
	row := q.db.QueryRow(ctx, getDoorById, id)
	var i Door
	err := row.Scan(
		&i.ID,
		&i.DoorName,
		&i.DeviceID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDoorPermissonByDoorId = `-- name: GetDoorPermissonByDoorId :one
SELECT dp.id, dp.door_id, r.role_name, dp.created_at
FROM door_permissons dp
JOIN roles r ON r.id = dp.role_id
WHERE door_id = $1
`

type GetDoorPermissonByDoorIdRow struct {
	ID        uuid.UUID          `json:"id"`
	DoorID    uuid.UUID          `json:"door_id"`
	RoleName  string             `json:"role_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetDoorPermissonByDoorId(ctx context.Context, doorID uuid.UUID) (GetDoorPermissonByDoorIdRow, error) {
	row := q.db.QueryRow(ctx, getDoorPermissonByDoorId, doorID)
	var i GetDoorPermissonByDoorIdRow
	err := row.Scan(
		&i.ID,
		&i.DoorID,
		&i.RoleName,
		&i.CreatedAt,
	)
	return i, err
}
