// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employees.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	optional "github.com/moznion/go-optional"
)

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (full_name, department)
VALUES($1, $2)
RETURNING id
`

type CreateEmployeeParams struct {
	FullName   string `json:"full_name"`
	Department string `json:"department"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createEmployee, arg.FullName, arg.Department)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const getEmployeeById = `-- name: GetEmployeeById :one
SELECT full_name, birth, department, created_at, updated_at
FROM employees
WHERE id = $1
`

type GetEmployeeByIdRow struct {
	FullName   string             `json:"full_name"`
	Birth      pgtype.Date        `json:"birth"`
	Department string             `json:"department"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetEmployeeById(ctx context.Context, id uuid.UUID) (GetEmployeeByIdRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeById, id)
	var i GetEmployeeByIdRow
	err := row.Scan(
		&i.FullName,
		&i.Birth,
		&i.Department,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEmployee = `-- name: UpdateEmployee :exec
UPDATE employees
SET
	full_name = COALESCE($1, full_name),
	birth = COALESCE($2, birth),
	department = COALESCE($3, department),
	updated_at = now()
WHERE id = $4
`

type UpdateEmployeeParams struct {
	FullName   optional.Option[string] `json:"full_name"`
	Birth      pgtype.Date             `json:"birth"`
	Department optional.Option[string] `json:"department"`
	ID         uuid.UUID               `json:"id"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) error {
	_, err := q.db.Exec(ctx, updateEmployee,
		arg.FullName,
		arg.Birth,
		arg.Department,
		arg.ID,
	)
	return err
}
