// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: employees.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	//"github.com/moznion/go-optional"
)

const getRoleIdByName = `-- name: GetRoleIdByName :one
SELECT id FROM roles WHERE role_name = $1
`

func (q *Queries) GetRoleIdByName(ctx context.Context, roleName string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getRoleIdByName, roleName)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO employees (role_id, full_name, department)
VALUES($1, $2, $3)
RETURNING id, full_name, birth, department, created_at, updated_at
`

type CreateEmployeeParams struct {
	RoleID     uuid.UUID `json:"role_id"`
	FullName   string    `json:"full_name"`
	Department string    `json:"department"`
}

type CreateEmployeeRow struct {
	ID         uuid.UUID          `json:"id"`
	FullName   string             `json:"full_name"`
	Birth      pgtype.Date        `json:"birth"`
	Department string             `json:"department"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (CreateEmployeeRow, error) {
	row := q.db.QueryRow(ctx, createEmployee, arg.RoleID, arg.FullName, arg.Department)
	var i CreateEmployeeRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Birth,
		&i.Department,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEmployeeById = `-- name: GetEmployeeById :one
SELECT e.id, e.full_name, e.birth, r.role_name, e.department, e.created_at, e.updated_at
FROM employees e
JOIN roles r ON r.id = e.role_id
WHERE e.id = $1
`

type GetEmployeeByIdRow struct {
	ID         uuid.UUID          `json:"id"`
	FullName   string             `json:"full_name"`
	Birth      pgtype.Date        `json:"birth"`
	RoleName   string             `json:"role_name"`
	Department string             `json:"department"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetEmployeeById(ctx context.Context, id uuid.UUID) (GetEmployeeByIdRow, error) {
	row := q.db.QueryRow(ctx, getEmployeeById, id)
	var i GetEmployeeByIdRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Birth,
		&i.RoleName,
		&i.Department,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateEmployee = `-- name: UpdateEmployee :exec
UPDATE employees
SET
	role_id    = COALESCE((SELECT id FROM roles WHERE role_name = $1), role_id),
	full_name  = COALESCE($2, full_name),
	birth      = COALESCE($3, birth),
	department = COALESCE($4, department),
	updated_at = now()
WHERE id = $5
`

type UpdateEmployeeParams struct {
	RoleName   *string     `json:"role_name"`
	FullName   *string     `json:"full_name"`
	Birth      pgtype.Date `json:"birth"`
	Department *string     `json:"department"`
	ID         uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) error {
	_, err := q.db.Exec(ctx, updateEmployee,
		arg.RoleName,
		arg.FullName,
		arg.Birth,
		arg.Department,
		arg.ID,
	)
	return err
}

const listEmployees = `-- name: ListEmployees :many
SELECT id, full_name, birth, department, created_at, updated_at
FROM employees
WHERE
    ($1::text IS NULL OR full_name ILIKE '%' || $1 || '%')
    AND ($2::text IS NULL OR department = $2)
    AND ($3::date IS NULL OR birth >= $3)
    AND ($4::date IS NULL OR birth <= $4)
    AND ($5::date IS NULL OR created_at::date >= $5)
    AND ($6::date IS NULL OR created_at::date <= $6)
ORDER BY created_at DESC
LIMIT $7 OFFSET $8
`

type ListEmployeesParams struct {
	Search      pgtype.Text `json:"search"`
	Department  pgtype.Text `json:"department"`
	BirthFrom   pgtype.Date `json:"birth_from"`
	BirthTo     pgtype.Date `json:"birth_to"`
	CreatedFrom pgtype.Date `json:"created_from"`
	CreatedTo   pgtype.Date `json:"created_to"`
	Limit       int32       `json:"limit"`
	Offset      int32       `json:"offset"`
}

type ListEmployeesRow struct {
	ID         uuid.UUID          `json:"id"`
	FullName   string             `json:"full_name"`
	Birth      pgtype.Date        `json:"birth"`
	Department string             `json:"department"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListEmployees(ctx context.Context, arg ListEmployeesParams) ([]ListEmployeesRow, error) {
	rows, err := q.db.Query(ctx, listEmployees,
		arg.Search,
		arg.Department,
		arg.BirthFrom,
		arg.BirthTo,
		arg.CreatedFrom,
		arg.CreatedTo,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []ListEmployeesRow
	for rows.Next() {
		var i ListEmployeesRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Birth,
			&i.Department,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const deleteEmployee = `-- name: DeleteEmployee :exec
DELETE FROM employees
WHERE id = $1
`

func (q *Queries) DeleteEmployee(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmployee, id)
	return err
}
