// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: enrollment_logs.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEnrollmentLogs = `-- name: CreateEnrollmentLogs :one
INSERT INTO enrollment_logs (employee_id, nfc_tag_uid, action, admin_id)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateEnrollmentLogsParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	NfcTagUid  string      `json:"nfc_tag_uid"`
	Action     Status      `json:"action"`
	AdminID    pgtype.UUID `json:"admin_id"`
}

func (q *Queries) CreateEnrollmentLogs(ctx context.Context, arg CreateEnrollmentLogsParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createEnrollmentLogs,
		arg.EmployeeID,
		arg.NfcTagUid,
		arg.Action,
		arg.AdminID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getEnrollmentLogs = `-- name: GetEnrollmentLogs :many
SELECT el.id, e.full_name, el.nfc_tag_uid, el.action, el.timestamp
FROM enrollment_logs el
JOIN employees e ON e.id = el.employee_id
JOIN users u ON u.id = el.employee_id
ORDER BY el.timestamp DESC
`

type GetEnrollmentLogsRow struct {
	ID        pgtype.UUID        `json:"id"`
	FullName  string             `json:"full_name"`
	NfcTagUid string             `json:"nfc_tag_uid"`
	Action    Status             `json:"action"`
	Timestamp pgtype.Timestamptz `json:"timestamp"`
}

func (q *Queries) GetEnrollmentLogs(ctx context.Context) ([]GetEnrollmentLogsRow, error) {
	rows, err := q.db.Query(ctx, getEnrollmentLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEnrollmentLogsRow
	for rows.Next() {
		var i GetEnrollmentLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.NfcTagUid,
			&i.Action,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
