// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: example.sql

package database

import (
	"context"
)

const getExamples = `-- name: GetExamples :many
SELECT id, description FROM examples
`

func (q *Queries) GetExamples(ctx context.Context) ([]Example, error) {
	rows, err := q.db.Query(ctx, getExamples)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Example
	for rows.Next() {
		var i Example
		if err := rows.Scan(&i.ID, &i.Description); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
