// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Action string

const (
	ActionEnroll Action = "enroll"
	ActionUpdate Action = "update"
	ActionRevoke Action = "revoke"
	ActionDelete Action = "delete"
)

func (e *Action) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Action(s)
	case string:
		*e = Action(s)
	default:
		return fmt.Errorf("unsupported scan type for Action: %T", src)
	}
	return nil
}

type NullAction struct {
	Action Action `json:"action"`
	Valid  bool   `json:"valid"` // Valid is true if Action is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAction) Scan(value interface{}) error {
	if value == nil {
		ns.Action, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Action.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAction) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Action), nil
}

type Result string

const (
	ResultAccepted Result = "accepted"
	ResultRejected Result = "rejected"
	ResultExisted  Result = "existed"
)

func (e *Result) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Result(s)
	case string:
		*e = Result(s)
	default:
		return fmt.Errorf("unsupported scan type for Result: %T", src)
	}
	return nil
}

type NullResult struct {
	Result Result `json:"result"`
	Valid  bool   `json:"valid"` // Valid is true if Result is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResult) Scan(value interface{}) error {
	if value == nil {
		ns.Result, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Result.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Result), nil
}

type Status string

const (
	StatusGranted Status = "granted"
	StatusDenied  Status = "denied"
)

func (e *Status) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Status(s)
	case string:
		*e = Status(s)
	default:
		return fmt.Errorf("unsupported scan type for Status: %T", src)
	}
	return nil
}

type NullStatus struct {
	Status Status `json:"status"`
	Valid  bool   `json:"valid"` // Valid is true if Status is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStatus) Scan(value interface{}) error {
	if value == nil {
		ns.Status, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Status.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Status), nil
}

type AccessLog struct {
	ID         uuid.UUID          `json:"id"`
	EmployeeID uuid.UUID          `json:"employee_id"`
	DoorID     uuid.UUID          `json:"door_id"`
	NfcTagID   uuid.UUID          `json:"nfc_tag_id"`
	Status     Status             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Door struct {
	ID        uuid.UUID          `json:"id"`
	DoorName  string             `json:"door_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type DoorPermisson struct {
	ID        uuid.UUID          `json:"id"`
	DoorID    uuid.UUID          `json:"door_id"`
	RoleID    uuid.UUID          `json:"role_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Employee struct {
	ID         uuid.UUID          `json:"id"`
	RoleID     uuid.UUID          `json:"role_id"`
	FullName   string             `json:"full_name"`
	Birth      pgtype.Date        `json:"birth"`
	Department string             `json:"department"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type EnrollmentLog struct {
	ID         uuid.UUID          `json:"id"`
	EmployeeID uuid.UUID          `json:"employee_id"`
	NfcTagUid  string             `json:"nfc_tag_uid"`
	Action     Action             `json:"action"`
	Result     Result             `json:"result"`
	AdminID    uuid.UUID          `json:"admin_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type NfcTag struct {
	ID         uuid.UUID          `json:"id"`
	Uid        string             `json:"uid"`
	EmployeeID uuid.UUID          `json:"employee_id"`
	IsActive   bool               `json:"is_active"`
	EnrolledBy uuid.UUID          `json:"enrolled_by"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Role struct {
	ID        uuid.UUID          `json:"id"`
	RoleName  string             `json:"role_name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID         uuid.UUID          `json:"id"`
	Username   string             `json:"username"`
	Password   string             `json:"password"`
	EmployeeID uuid.UUID          `json:"employee_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
