// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Example struct {
	ID          int32       `json:"id"`
	Description pgtype.Text `json:"description"`
}
