// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nfc_tags.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNfcTag = `-- name: CreateNfcTag :one
INSERT INTO nfc_tags (employee_id, uid, is_active, enrolled_by)
VALUES($1, $2, $3, $4)
RETURNING id
`

type CreateNfcTagParams struct {
	EmployeeID pgtype.UUID `json:"employee_id"`
	Uid        string      `json:"uid"`
	IsActive   bool        `json:"is_active"`
	EnrolledBy pgtype.UUID `json:"enrolled_by"`
}

func (q *Queries) CreateNfcTag(ctx context.Context, arg CreateNfcTagParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createNfcTag,
		arg.EmployeeID,
		arg.Uid,
		arg.IsActive,
		arg.EnrolledBy,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const filterTags = `-- name: FilterTags :many
SELECT nfc_tags.uid, employees.full_name, is_active, nfc_tags.created_at
FROM nfc_tags
JOIN employees ON employees.id = nfc_tags.employee_id
WHERE
(
    ($1::boolean IS NULL OR is_active = $1)
)
`

type FilterTagsRow struct {
	Uid       string             `json:"uid"`
	FullName  string             `json:"full_name"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) FilterTags(ctx context.Context, isActive pgtype.Bool) ([]FilterTagsRow, error) {
	rows, err := q.db.Query(ctx, filterTags, isActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FilterTagsRow
	for rows.Next() {
		var i FilterTagsRow
		if err := rows.Scan(
			&i.Uid,
			&i.FullName,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagById = `-- name: GetTagById :one
SELECT nfc_tags.id, uid, nfc_tags.employee_id, is_active, enrolled_by, nfc_tags.created_at, employees.id, role_id, full_name, birth, department, employees.created_at, updated_at, users.id, username, password, users.employee_id, users.created_at
FROM nfc_tags
JOIN employees ON employees.id = nfc_tags.employee_id
JOIN users ON users.id = nfc_tags.enrolled_by
WHERE nfc_tags.id = $1
`

type GetTagByIdRow struct {
	ID           pgtype.UUID        `json:"id"`
	Uid          string             `json:"uid"`
	EmployeeID   pgtype.UUID        `json:"employee_id"`
	IsActive     bool               `json:"is_active"`
	EnrolledBy   pgtype.UUID        `json:"enrolled_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	ID_2         pgtype.UUID        `json:"id_2"`
	RoleID       pgtype.UUID        `json:"role_id"`
	FullName     string             `json:"full_name"`
	Birth        pgtype.Date        `json:"birth"`
	Department   string             `json:"department"`
	CreatedAt_2  pgtype.Timestamptz `json:"created_at_2"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ID_3         pgtype.UUID        `json:"id_3"`
	Username     string             `json:"username"`
	Password     string             `json:"password"`
	EmployeeID_2 uuid.UUID          `json:"employee_id_2"`
	CreatedAt_3  pgtype.Timestamptz `json:"created_at_3"`
}

func (q *Queries) GetTagById(ctx context.Context, id pgtype.UUID) (GetTagByIdRow, error) {
	row := q.db.QueryRow(ctx, getTagById, id)
	var i GetTagByIdRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.EmployeeID,
		&i.IsActive,
		&i.EnrolledBy,
		&i.CreatedAt,
		&i.ID_2,
		&i.RoleID,
		&i.FullName,
		&i.Birth,
		&i.Department,
		&i.CreatedAt_2,
		&i.UpdatedAt,
		&i.ID_3,
		&i.Username,
		&i.Password,
		&i.EmployeeID_2,
		&i.CreatedAt_3,
	)
	return i, err
}

const updateTagStatus = `-- name: UpdateTagStatus :exec
UPDATE nfc_tags
SET
    is_active = COALESCE($1, is_active)
WHERE id = $2
`

type UpdateTagStatusParams struct {
	IsActive pgtype.Bool `json:"is_active"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateTagStatus(ctx context.Context, arg UpdateTagStatusParams) error {
	_, err := q.db.Exec(ctx, updateTagStatus, arg.IsActive, arg.ID)
	return err
}
