// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nfc_tags.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const checkUidExist = `-- name: CheckUidExist :one
SELECT nt.id, nt.uid
FROM nfc_tags nt
WHERE nt.uid = $1
`

type CheckUidExistRow struct {
	ID  uuid.UUID `json:"id"`
	Uid string    `json:"uid"`
}

func (q *Queries) CheckUidExist(ctx context.Context, uid string) (CheckUidExistRow, error) {
	row := q.db.QueryRow(ctx, checkUidExist, uid)
	var i CheckUidExistRow
	err := row.Scan(&i.ID, &i.Uid)
	return i, err
}

const createNfcTag = `-- name: CreateNfcTag :one
INSERT INTO nfc_tags (uid)
VALUES($1)
RETURNING id
`

func (q *Queries) CreateNfcTag(ctx context.Context, uid string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createNfcTag, uid)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const filterTags = `-- name: FilterTags :many
SELECT nfc_tags.uid, employees.full_name, is_active, nfc_tags.created_at
FROM nfc_tags
JOIN employees ON employees.id = nfc_tags.employee_id
WHERE
(
    ($1::boolean IS NULL OR is_active = $1)
)
`

type FilterTagsRow struct {
	Uid       string             `json:"uid"`
	FullName  string             `json:"full_name"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) FilterTags(ctx context.Context, isActive pgtype.Bool) ([]FilterTagsRow, error) {
	rows, err := q.db.Query(ctx, filterTags, isActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FilterTagsRow
	for rows.Next() {
		var i FilterTagsRow
		if err := rows.Scan(
			&i.Uid,
			&i.FullName,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagById = `-- name: GetTagById :one
SELECT nt.id, nt.uid, nt.is_active, nt.employee_id, e.full_name, r.role_name, nt.created_at, nt.updated_at
FROM nfc_tags nt
JOIN employees e ON e.id = nt.employee_id
JOIN roles r ON r.id = e.role_id
WHERE nt.id = $1
`

type GetTagByIdRow struct {
	ID         uuid.UUID          `json:"id"`
	Uid        string             `json:"uid"`
	IsActive   bool               `json:"is_active"`
	EmployeeID uuid.UUID          `json:"employee_id"`
	FullName   string             `json:"full_name"`
	RoleName   string             `json:"role_name"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTagById(ctx context.Context, id uuid.UUID) (GetTagByIdRow, error) {
	row := q.db.QueryRow(ctx, getTagById, id)
	var i GetTagByIdRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.IsActive,
		&i.EmployeeID,
		&i.FullName,
		&i.RoleName,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTagByUid = `-- name: GetTagByUid :one
SELECT nt.id, nt.uid, e.full_name, nt.employee_id, nt.created_at, nt.updated_at
FROM nfc_tags nt
JOIN employees e ON e.id = nt.employee_id
WHERE nt.uid = $1
`

type GetTagByUidRow struct {
	ID         uuid.UUID          `json:"id"`
	Uid        string             `json:"uid"`
	FullName   string             `json:"full_name"`
	EmployeeID uuid.UUID          `json:"employee_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTagByUid(ctx context.Context, uid string) (GetTagByUidRow, error) {
	row := q.db.QueryRow(ctx, getTagByUid, uid)
	var i GetTagByUidRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.FullName,
		&i.EmployeeID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTagStatus = `-- name: UpdateTagStatus :one
UPDATE nfc_tags
SET
    is_active = $1
WHERE id = $2 AND is_active = true
RETURNING id
`

type UpdateTagStatusParams struct {
	IsActive bool      `json:"is_active"`
	ID       uuid.UUID `json:"id"`
}

func (q *Queries) UpdateTagStatus(ctx context.Context, arg UpdateTagStatusParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, updateTagStatus, arg.IsActive, arg.ID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
