// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: nfc_tags.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNfcTag = `-- name: CreateNfcTag :one
INSERT INTO nfc_tags (employee_id, uid, is_active, enrolled_by)
VALUES($1, $2, $3, $4)
RETURNING id
`

type CreateNfcTagParams struct {
	EmployeeID uuid.UUID `json:"employee_id"`
	Uid        string    `json:"uid"`
	IsActive   bool      `json:"is_active"`
	EnrolledBy uuid.UUID `json:"enrolled_by"`
}

func (q *Queries) CreateNfcTag(ctx context.Context, arg CreateNfcTagParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createNfcTag,
		arg.EmployeeID,
		arg.Uid,
		arg.IsActive,
		arg.EnrolledBy,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const filterTags = `-- name: FilterTags :many
SELECT nfc_tags.uid, employees.full_name, is_active, nfc_tags.created_at
FROM nfc_tags
JOIN employees ON employees.id = nfc_tags.employee_id
WHERE
(
    ($1::boolean IS NULL OR is_active = $1)
)
`

type FilterTagsRow struct {
	Uid       string             `json:"uid"`
	FullName  string             `json:"full_name"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) FilterTags(ctx context.Context, isActive pgtype.Bool) ([]FilterTagsRow, error) {
	rows, err := q.db.Query(ctx, filterTags, isActive)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FilterTagsRow
	for rows.Next() {
		var i FilterTagsRow
		if err := rows.Scan(
			&i.Uid,
			&i.FullName,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTagById = `-- name: GetTagById :one
SELECT nt.id, nt.uid, nt.is_active, e.full_name, u.username, nt.created_at, nt.updated_at
FROM nfc_tags nt
JOIN employees e ON e.id = nt.employee_id
JOIN users u ON u.id = nt.enrolled_by
WHERE nt.id = $1
`

type GetTagByIdRow struct {
	ID        uuid.UUID          `json:"id"`
	Uid       string             `json:"uid"`
	IsActive  bool               `json:"is_active"`
	FullName  string             `json:"full_name"`
	Username  string             `json:"username"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetTagById(ctx context.Context, id uuid.UUID) (GetTagByIdRow, error) {
	row := q.db.QueryRow(ctx, getTagById, id)
	var i GetTagByIdRow
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.IsActive,
		&i.FullName,
		&i.Username,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTagStatus = `-- name: UpdateTagStatus :exec
UPDATE nfc_tags
SET
    is_active = COALESCE($1, is_active)
WHERE id = $2
`

type UpdateTagStatusParams struct {
	IsActive pgtype.Bool `json:"is_active"`
	ID       uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateTagStatus(ctx context.Context, arg UpdateTagStatusParams) error {
	_, err := q.db.Exec(ctx, updateTagStatus, arg.IsActive, arg.ID)
	return err
}
