// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package database

import (
	"context"

	"github.com/google/uuid"
	optional "github.com/moznion/go-optional"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (role_name)
VALUES($1)
RETURNING id
`

func (q *Queries) CreateRole(ctx context.Context, roleName string) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createRole, roleName)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const listRoles = `-- name: ListRoles :many
SELECT id, role_name, created_at FROM roles
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.RoleName, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRoleName = `-- name: SearchRoleName :many
SELECT id, role_name, created_at FROM roles
WHERE role_name LIKE '%' || $1 || '%'
`

func (q *Queries) SearchRoleName(ctx context.Context, roleName optional.Option[string]) ([]Role, error) {
	rows, err := q.db.Query(ctx, searchRoleName, roleName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(&i.ID, &i.RoleName, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
